# coding: utf-8

"""
    PyBloods

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pybloodsclient
from pybloodsclient.api.default_api import DefaultApi  # noqa: E501
from pybloodsclient.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = pybloodsclient.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_note_group_id_get(self):
        """Test case for note_group_id_get

        Return a list of notes  # noqa: E501
        """
        pass

    def test_note_groups_get(self):
        """Test case for note_groups_get

        Return a list of all available note groups  # noqa: E501
        """
        pass

    def test_observations_get(self):
        """Test case for observations_get

        Return a list of all observations  # noqa: E501
        """
        pass

    def test_observations_post(self):
        """Test case for observations_post

        Create a new observation  # noqa: E501
        """
        pass

    def test_providers_get(self):
        """Test case for providers_get

        Return a list of all available healthcare providers  # noqa: E501
        """
        pass

    def test_samples_get(self):
        """Test case for samples_get

        Return a list of all available samples  # noqa: E501
        """
        pass

    def test_sources_get(self):
        """Test case for sources_get

        Return a list of all available sources  # noqa: E501
        """
        pass

    def test_unit_id_get(self):
        """Test case for unit_id_get

        Return a unit  # noqa: E501
        """
        pass

    def test_units_get(self):
        """Test case for units_get

        Return a list of all available units  # noqa: E501
        """
        pass

    def test_units_post(self):
        """Test case for units_post

        Create a new unit  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
