# coding: utf-8

"""
    PyBloods

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pybloodsclient
from models.new_unit import NewUnit  # noqa: E501
from pybloodsclient.rest import ApiException


class TestNewUnit(unittest.TestCase):
    """NewUnit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNewUnit(self):
        """Test NewUnit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pybloodsclient.models.new_unit.NewUnit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
