# coding: utf-8

"""
    PyBloods

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pybloodsclient
from pybloodsclient.models.new_unit import NewUnit  # noqa: E501
from pybloodsclient.rest import ApiException


class TestNewUnit(unittest.TestCase):
    """NewUnit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNewUnit(self):
        """Test NewUnit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pybloodsclient.models.new_unit.NewUnit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
