# coding: utf-8

"""
    PyBloods

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class NewNote(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'content': 'str',
        'documents': 'list[str]',
        'language': 'str',
        'note_group_id': 'int'
    }

    attribute_map = {
        'content': 'content',
        'documents': 'documents',
        'language': 'language',
        'note_group_id': 'note_group_id'
    }

    def __init__(self, content=None, documents=None, language=None, note_group_id=None):  # noqa: E501
        """NewNote - a model defined in OpenAPI"""  # noqa: E501

        self._content = None
        self._documents = None
        self._language = None
        self._note_group_id = None
        self.discriminator = None

        self.content = content
        self.documents = documents
        self.language = language
        self.note_group_id = note_group_id

    @property
    def content(self):
        """Gets the content of this NewNote.  # noqa: E501


        :return: The content of this NewNote.  # noqa: E501
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this NewNote.


        :param content: The content of this NewNote.  # noqa: E501
        :type: str
        """
        if content is None:
            raise ValueError("Invalid value for `content`, must not be `None`")  # noqa: E501

        self._content = content

    @property
    def documents(self):
        """Gets the documents of this NewNote.  # noqa: E501


        :return: The documents of this NewNote.  # noqa: E501
        :rtype: list[str]
        """
        return self._documents

    @documents.setter
    def documents(self, documents):
        """Sets the documents of this NewNote.


        :param documents: The documents of this NewNote.  # noqa: E501
        :type: list[str]
        """
        if documents is None:
            raise ValueError("Invalid value for `documents`, must not be `None`")  # noqa: E501

        self._documents = documents

    @property
    def language(self):
        """Gets the language of this NewNote.  # noqa: E501


        :return: The language of this NewNote.  # noqa: E501
        :rtype: str
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this NewNote.


        :param language: The language of this NewNote.  # noqa: E501
        :type: str
        """
        if language is None:
            raise ValueError("Invalid value for `language`, must not be `None`")  # noqa: E501

        self._language = language

    @property
    def note_group_id(self):
        """Gets the note_group_id of this NewNote.  # noqa: E501


        :return: The note_group_id of this NewNote.  # noqa: E501
        :rtype: int
        """
        return self._note_group_id

    @note_group_id.setter
    def note_group_id(self, note_group_id):
        """Sets the note_group_id of this NewNote.


        :param note_group_id: The note_group_id of this NewNote.  # noqa: E501
        :type: int
        """
        if note_group_id is None:
            raise ValueError("Invalid value for `note_group_id`, must not be `None`")  # noqa: E501

        self._note_group_id = note_group_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NewNote):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
