# coding: utf-8

"""
    PyBloods

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class NoteGroup(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'note_group_id': 'int'
    }

    attribute_map = {
        'note_group_id': 'note_group_id'
    }

    def __init__(self, note_group_id=None):  # noqa: E501
        """NoteGroup - a model defined in OpenAPI"""  # noqa: E501

        self._note_group_id = None
        self.discriminator = None

        self.note_group_id = note_group_id

    @property
    def note_group_id(self):
        """Gets the note_group_id of this NoteGroup.  # noqa: E501


        :return: The note_group_id of this NoteGroup.  # noqa: E501
        :rtype: int
        """
        return self._note_group_id

    @note_group_id.setter
    def note_group_id(self, note_group_id):
        """Sets the note_group_id of this NoteGroup.


        :param note_group_id: The note_group_id of this NoteGroup.  # noqa: E501
        :type: int
        """
        if note_group_id is None:
            raise ValueError("Invalid value for `note_group_id`, must not be `None`")  # noqa: E501

        self._note_group_id = note_group_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NoteGroup):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
