# coding: utf-8

"""
    PyBloods

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from pybloodsclient.models.new_observation import NewObservation  # noqa: F401,E501


class Observation(NewObservation):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'observation_id': 'int'
    }

    attribute_map = {
        'observation_id': 'observation_id'
    }

    def __init__(self, observation_id=None):  # noqa: E501
        """Observation - a model defined in Swagger"""  # noqa: E501
        self._observation_id = None
        self.discriminator = None
        self.observation_id = observation_id

    @property
    def observation_id(self):
        """Gets the observation_id of this Observation.  # noqa: E501


        :return: The observation_id of this Observation.  # noqa: E501
        :rtype: int
        """
        return self._observation_id

    @observation_id.setter
    def observation_id(self, observation_id):
        """Sets the observation_id of this Observation.


        :param observation_id: The observation_id of this Observation.  # noqa: E501
        :type: int
        """
        if observation_id is None:
            raise ValueError("Invalid value for `observation_id`, must not be `None`")  # noqa: E501

        self._observation_id = observation_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Observation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Observation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
